apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycv.fullname" . }}
  labels:
    {{- include "mycv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7990
      protocol: TCP
      name: http
  selector:
    {{- include "mycv.selectorLabels" . | nindent 4 }}
